//go:build ignore

// gen_tints writes tints_gen.go: bubbletint's built-in themes as a compact
// table. Run it from the repository root after changing the bubbletint
// version in go.mod:
//
//	go run ./internal/theme/gen_tints.go
//
// bubbletint defines each of its 342 themes as a *Tint literal with twenty
// *Color pointers, and NewDefaultRegistry links every one: about 200 KB of
// pointer-laden data. tints_gen.go holds the same themes as one string of
// RGB bytes and a table of names, and builtinTints builds the *Tint values
// when the registry is first filled. The tint package's registry, types
// and functions are used as before.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"

	tint "github.com/lrstanley/bubbletint/v2"
)

func main() {
	all := tint.DefaultTints()
	def := tint.TintDraculaPlus

	var colors strings.Builder
	var b bytes.Buffer
	b.WriteString("// Code generated by gen_tints.go from github.com/lrstanley/bubbletint/v2; DO NOT EDIT.\n\n")
	b.WriteString("// The themes come from iTerm2-Color-Schemes by way of bubbletint (MIT).\n\n")
	b.WriteString("package theme\n\n")
	fmt.Fprintf(&b, "// builtinDefaultTint is the ID of the tint bubbletint's default registry\n// starts on.\nconst builtinDefaultTint = %q\n\n", def.ID)
	b.WriteString("// builtinTintTable is each built-in tint's name, ID, darkness and credits,\n// in bubbletint's order. Its colours are in builtinTintColors.\n")
	b.WriteString("var builtinTintTable = [...]builtinTintInfo{\n")
	for _, t := range all {
		fmt.Fprintf(&b, "\t{%q, %q, %v, ", t.DisplayName, t.ID, t.Dark)
		// nil and empty differ in bubbletint's data, so they differ here.
		if t.CreditSources == nil {
			b.WriteString("nil},\n")
		} else {
			b.WriteString("[]builtinCredit{")
			for i, c := range t.CreditSources {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "{%q, %q}", c.Name, c.Link)
			}
			b.WriteString("}},\n")
		}
		for _, c := range tintSlots(t) {
			if c == nil {
				colors.WriteString("\x00\x00\x00\x00")
				continue
			}
			if c.A != 255 {
				panic(fmt.Sprintf("%s: a colour with alpha %d; the table stores opaque colours only", t.ID, c.A))
			}
			colors.Write([]byte{1, c.R, c.G, c.B})
		}
	}
	b.WriteString("}\n\n")
	b.WriteString("// builtinTintColors holds builtinTintSlots colours per tint, four bytes each:\n// 1 and R, G, B for a colour, four zeros for a slot the tint leaves unset.\n")
	fmt.Fprintf(&b, "const builtinTintColors = %q\n", colors.String())

	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("internal/theme/tints_gen.go", src, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %d tints\n", len(all))
}

// tintSlots must list the fields in the order tints.go's builtinTints reads
// them back.
func tintSlots(t *tint.Tint) []*tint.Color {
	return []*tint.Color{
		t.Fg, t.Bg, t.SelectionBg, t.Cursor,
		t.BrightBlack, t.BrightBlue, t.BrightCyan, t.BrightGreen,
		t.BrightPurple, t.BrightRed, t.BrightWhite, t.BrightYellow,
		t.Black, t.Blue, t.Cyan, t.Green,
		t.Purple, t.Red, t.White, t.Yellow,
	}
}
